### ISSUE TITLE
it looks the dataset are corrupt

### ISSUE THREAD

**Issue by loveJasmine** [MdAsifKhan/Commonsense-Knowledge-Base-Completion#1]
mldl@ub1604:~/ub16_prj/Commonsense-Knowledge-Base-Completion$ gzip -d tuples.cn.txt.gz 

gzip: tuples.cn.txt.gz: not in gzip format
mldl@ub1604:~/ub16_prj/Commonsense-Knowledge-Base-Completion$ gzip -d ckbc-demo.tar.gz 

gzip: ckbc-demo.tar.gz: not in gzip format
mldl@ub1604:~/ub16_prj/Commonsense-Knowledge-Base-Completion$ tar zxvf ckbc-demo.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mldl@ub1604:~/ub16_prj/Commonsense-Knowledge-Base-Completion$

**Comment by MdAsifKhan** [comment]
data in text format
